-- Add profile settings columns
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS rest_time INTEGER DEFAULT 90,
  ADD COLUMN IF NOT EXISTS timer_sound BOOLEAN DEFAULT true,
  ADD COLUMN IF NOT EXISTS lang TEXT DEFAULT 'fr',
  ADD COLUMN IF NOT EXISTS weight DECIMAL,
  ADD COLUMN IF NOT EXISTS height DECIMAL,
  ADD COLUMN IF NOT EXISTS age INTEGER,
  ADD COLUMN IF NOT EXISTS goal TEXT;
